### PR TITLE
allows a user to post comments

### PR DESCRIPTION
**Pull request by conorhutchins**

### CODE REVIEW

**Review by dappernerddesigns — CHANGES_REQUESTED** [review]
I like that you've got the forms stopping anyone posting without a username or text. At this point I'd consider either hard coding a user on the post request, or looking into useContext. It is quite odd to type in your username before commenting. For a sleeker experience maybe hard code a user for now.

You have a small problem when posting a comment, the comments get stuck in a permanent loading phase. On a refresh they've come back from the server correctly which is great, but your optimistic rendering is a bit off.

Love the error if offline though, really well done. 

See if you can fix the optimistic render and resubmit for us please.

**Comment by conorhutchins** [comment]
andy about summed it up for me 
https://www.youtube.com/watch?v=N9RMtaZz1Cc&ab_channel=andyyyc

**Comment by conorhutchins** [comment]
im half the man i was before this ticket

**Review by dappernerddesigns — APPROVED** [review]
Well done! The Andy Murry link made me almost spill my coffee. Fantastic effort.

**Pull request merged**
